### ISSUE TITLE
Append : 5 NO ERREUR #23505 

### ISSUE THREAD

**Issue by worddevfr** [MFAshby/gomail#2]
221 Goodnight and good luck
* OK [CAPABILITY IMAP4rev1 STARTTLS LOGINDISABLED] IMAP4rev1 Service Ready
1 STARTTLS
1 OK Begin TLS negotiation now
* CAPABILITY IMAP4rev1 AUTH=PLAIN
2 capability
* CAPABILITY IMAP4rev1 AUTH=PLAIN
2 OK CAPABILITY completed
3 authenticate plain
+
3 OK [CAPABILITY IMAP4rev1] AUTHENTICATE completed
4 select "Drafts"
2017/12/28 00:38:06 ***USER***  test@example.com
* OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft \Recent)] Flags permitted.
* OK [UIDNEXT 1] Predicted next UID
* OK [UIDVALIDITY 1] UIDs valid
* 0 EXISTS
* 0 RECENT
4 OK [READ-WRITE] SELECT completed
5 append "Drafts" (\Draft) {648}
+ send literal
FCC: imap://test%40example.com@localhost/SENT
X-Identity-Key: id4
X-Account-Key: account15
To: "test@example.com" <test@example.com>
From: "test@example.com" <test@example.com>
Subject: my Subject
Message-ID: <6d232b1b-e5ca-37eb-952f-be151ea7bd0e@example.com>
Date: Thu, 28 Dec 2017 00:38:05 +0100
X-Mozilla-Draft-Info: internal/draft; vcard=0; receipt=0; DSN=0; uuencode=0;
 attachmentreminder=0
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101
 Thunderbird/45.8.0
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 7bit

my msg

2017/12/28 00:38:06 ***USER***  test@example.com
_**5 NO ERREUR #23505 la valeur d'une clé dupliquée rompt la contrainte unique « messages_pkey » (addr="[::1]:5432")**_

**Comment by MFAshby** [comment]
Replication:
Connect thunderbird to gomail
Write an email, save as draft
Write a second email, save as draft
Get duplicate key error from postgres as above.

The problem is happening because the server is trying to use the uidNext function instead of just letting the database assign UID.

**Comment by MFAshby** [comment]
Fixed, please pull the latest version and try again.
Thanks for contributing!

**Comment by MFAshby** [comment]
ref. https://github.com/MFAshby/gomailpg/commit/beff6404b8211142c5b66281e22b0e525d5d8045
